### ISSUE TITLE
Latex Template: keeplastbox option removed from flushend

### ISSUE THREAD

**Issue by JoschD** [JACoW-org/JACoW_Templates#3]
In the new version of `flushend` (v4 from 2021, https://www.ctan.org/pkg/flushend) `keeplastbox` has been removed as setting (I think it's default now). As this is still in the `jacow.cls` (in line 200) this class cannot be used on systems with the newer version installed.

Simply removing the setting fixes the issue. 
`\RequirePackage{flushend}`

**Comment by vrws** [comment]
Please just remove the parameter "keeplastbox" in the call to jacow.cls, then there will only be a warning that the parameter is deprecated in the log.

Volker RW Schaa

**Comment by JoschD** [comment]
I cannot confirm. 
```
\RequirePackage[keeplastbox]{flushend}
``` 

is hardcoded, so no matter if I give it to the class or not I get



```
(/usr/local/texlive/2021/texmf-dist/tex/latex/sttools/flushend.sty
Package: flushend 2021/10/04 v4.0 Balancing columns in twocolumn mode

/usr/local/texlive/2021/texmf-dist/tex/latex/sttools/flushend.sty:83: LaTeX Error: Unknown option `keeplastbox' for package `flushend'.
```

I would agree with your solution, if there was something like
```
\DeclareOption{keeplastbox}{\PassOptionsToPackage{keeplastbox}{flushend}}
\RequirePackage{flushend}
```
in the class (but there isn't)

**Comment by fsoubelet** [comment]
> Please just remove the parameter "keeplastbox" in the call to jacow.cls, then there will only be a warning that the parameter is deprecated in the log. Volker RW Schaa
> […](#)
> On April 14, 2022 12:24:28 JoschD ***@***.***> wrote: In the new version of flushend (v4 from 2021, https://www.ctan.org/pkg/flushend) keeplastbox has been removed as setting (I think it's default now). As this is still in the jacow.cls this class cannot be used on systems with the newer version installed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

Hi, I have tried this but the option is still required during compile time and the builds fail.

**Comment by vrws** [comment]
OK, I will try to check this soon as I'm currently not close to my computer.
I already have a new release prepared but it's not yet published on CTAN. I will make this available for testing.
Volker

**Comment by JoschD** [comment]
Very nice! 
I would be happy to test. 
Thank you very much.

Cheers,
Josch

**Comment by vrws** [comment]
Dear Josch,

sorry — you were right about the hardwired option for flushend — I planned it differently but obviously have never uploaded the modified version v2.4a which removed the parameter in \Requirepackage as it was present in the option list example in the published JACoW template.

I've placed 'newer' versions for test on JACoW.org (https://www.jacow.org/Authors/LaTeX) mainly v2.5 and for BibLaTeX users v2.7 are the interesting ones.

I hope that you will have a chance to test, then I will quickly publish it on GitHub and CTAN.

All the best,
    Volker

**Comment by fsoubelet** [comment]
I can also confirm that v2.7 works nicely for me! Hopefully it gets officially published soon :)

**Comment by vrws** [comment]
Hi Joshua,
thanks for the test and thumbs up.

I've introduced the BibLaTeX fixes as an intermediate solution before we have an own 'JACoW' BibLaTeX style file. Patching the original macros is really cumbersome and error-prone.


Btw. I was accepting BibLaTeX file for IPACs and other JACoW conferences since quite some time. Maybe other editors didn't know that.


The new version is on CTAN, but has probably to be provided on GitHub and OverLeaf too, but I'm on vacation without my laptop...


Thanks and all the best,
Volker

**Comment by vrws** [comment]
Hi Felix,
thanks for the testing and confirmation that v2.7 works.
Concerning publication see what I answered Joshua.

Thanks and best regards,
Volker

**Comment by afcuttin** [comment]
> Please just remove the parameter "keeplastbox" in the call to jacow.cls, then there will only be a warning that the parameter is deprecated in the log. Volker RW Schaa
> […](#)
> On April 14, 2022 12:24:28 JoschD ***@***.***> wrote: In the new version of flushend (v4 from 2021, https://www.ctan.org/pkg/flushend) keeplastbox has been removed as setting (I think it's default now). As this is still in the jacow.cls this class cannot be used on systems with the newer version installed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

Shouldn't this be reflected also in the template?

**Comment by vrws** [comment]
the new version v2.7 solves this issue.
