### ISSUE TITLE
Is fixltx2e still needed?

### ISSUE THREAD

**Issue by afcuttin** [JACoW-org/JACoW_Templates#4]
Using the latest available LaTeX template (v 2.3  Feb 2019) I get the following warning:

`/usr/local/texlive/2019/texmf-dist/tex/latex/base/fixltx2e.sty: Package fixltx2e Warning: fixltx2e is not required with releases after 2015(fixltx2e)                All fixes are now in the LaTeX kernel.`

Is `fixltx2e` still needed?

**Comment by vrws** [comment]
Please download the latest version from CTAN v2.7), there are more fixes for current LaTeX incorporated.

Volker

**Comment by afcuttin** [comment]
So basically the version here on github is behind the one available on CTAN, is it?

**Comment by vrws** [comment]
Yes, I didn't manage to update it.
Volker

**Comment by afcuttin** [comment]
Ok, thanks.
So it is safe to assume that v2.7 can be used for IPAC proceedings?
Because "available for testing" can be misleading.
This has gone slightly off-topic wrt the title, but thanks anyway

**Comment by vrws** [comment]
Yes, definitely for IPAC'22 and all other JACoW conferences.
I'm already in Bangkok as we start editing on Thursday. As I see, you are not presenting TUPOMS062, so I won't meet you.

All the best,
   Volker

**Comment by vrws** [comment]
the new version v2.7 solves this issue.

**Comment by afcuttin** [comment]
Indeed, this time I won't attend the conference. My colleague will.
Hope to see you next year in Venezia!

I'd be happy to contribute with the class development/testing, btw

Il lun 6 giu 2022, 19:03 Volker RW Schaa ***@***.***> ha
scritto:

> Yes, definitely for IPAC'22 and all other JACoW conferences.
> I'm already in Bangkok as we start editing on Thursday. As I see, you are
> not presenting TUPOMS062, so I won't meet you.
>
> All the best,
> Volker
>
>
