### ISSUE TITLE
Incompatibility between LaTeX template and `tikz` `external` package

### ISSUE THREAD

**Issue by AdrienPlacais** [JACoW-org/JACoW_Templates#8]
I've encountered an issue where there is an incompatibility between the provided LaTeX template and the `tikz` `external` package. According to the [TikZ documentation](https://tikz.dev/library-external#sec-52.8.2), the `pdfpages` package, which is loaded by default in the template, interferes with the externalization feature of TikZ.

Suggested Solutions:
- Disable optimization: add the option `\tikzexternalize[optimize=false]` to your document. This solution works best if your TikZ pictures are relatively lightweight.
- Deactivate `pdfpages`: deactivate the loading of the `pdfpages` package when you need to compile the figures.

This issue took me way too long to troubleshoot, and I believe others may encounter the same problem. It would be helpful if this information could be added to the FAQ, README, or other documentation to assist future users.

**Comment by vrws** [comment]
Dear Adrien,

Please just remove the packages "pdfpages, multirow, ..." from the template. As the comment above the line states, these packages are only used for the documentation.
Only packages in the JACoW class file are used abd needed.

The next version of the class file will separate this more clearly.

Thank you for the report, after my vacation I will try to publish a new version of the class and template,
   Volker

**Comment by AdrienPlacais** [comment]
Thanks for the quick answer!! :)
